### ISSUE TITLE
converting language from ar to eng or reverse

### ISSUE THREAD

**Issue by lamatat** [MoathOthman/MOLH#17] opened 2018-05-29 10:47 UTC
am getting this error when changing the language to eng from ar 

![screen shot 2018-05-29 at 1 44 29 pm](https://user-images.githubusercontent.com/39458325/40654339-b16cade6-6346-11e8-96d2-7df91ffa09a9.png)
 
what is this error and how to solve it please?

thanks in advance..

**Comment by lamatat** [comment] 2018-05-30 11:39
any news about this?

**Comment by MoathOthman** [comment] 2018-05-30 11:41
Hey
let me check it later on tonight .

Sent from my iPhone

On May 30, 2018, at 2:39 PM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


any news about this?

**Comment by MoathOthman** [comment] 2018-05-30 11:42
If you can give me more info about the environment,
Have you tried the demo project?
Can you reproduce the issue there?

Sent from my iPhone

On May 30, 2018, at 2:39 PM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


any news about this?

**Comment by lamatat** [comment] 2018-05-30 11:45
yes i did tried it .. i will try doing that and let you know ..

**Comment by lamatat** [comment] 2018-05-30 11:49
i just tried but didn't know how to do it x_x
but i think this happened when i used MOLHLanguage.isArabic()

**Comment by MoathOthman** [comment] 2018-05-30 11:50
What happens if you use isRTL instead

Sent from my iPhone

On May 30, 2018, at 2:49 PM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


i just tried but didn't know how to do it x_x
but i think this happened when i used MOLHLanguage.isArabic()

**Comment by lamatat** [comment] 2018-05-30 12:00
got same error ...

trie to comment them all .. and worked without errors .. so the problem is really from MOLHLanguage.isArabic() and MOLHLanguage.isRTL()

but i need to know if its arabic or not so i need to use one of them :(

if you please can help me solve this 

thanks in advance!

**Comment by MoathOthman** [comment] 2018-05-30 12:12
what are the languages you are supporting and how many?

Sent from my iPhone

On May 30, 2018, at 3:00 PM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


got same error ...

trie to comment them all .. and worked without errors .. so the problem is really from MOLHLanguage.isArabic() and MOLHLanguage.isRTL()

but i need to know if its arabic or not so i need to use one of them :(

if you please can help me solve this

thanks in advance!

**Comment by lamatat** [comment] 2018-05-30 12:16
just two .. english and arabic

**Comment by MoathOthman** [comment] 2018-05-30 12:19
can you replace the function with this 
 /// get current Apple language
    public class func currentAppleLanguage() -> String {
        let userdef = UserDefaults.standard
        let langArray = userdef.object(forKey: APPLE_LANGUAGE_KEY) as! NSArray
        let current = langArray.firstObject as! String
        let currentWithoutLocale = current.substring(to: current.index(current.startIndex, offsetBy: 2))
        return currentWithoutLocale
    }

**Comment by lamatat** [comment] 2018-05-30 12:26
![screen shot 2018-05-30 at 3 25 48 pm](https://user-images.githubusercontent.com/39458325/40719930-c1d0794c-641d-11e8-81a4-1e638f537a77.png)

got the same error in next function ...

**Comment by MoathOthman** [comment] 2018-05-30 12:29
Ok then please use the latest commit then , the release is not updated apparently .
U can do that on your podfile

Sent from my iPhone

On May 30, 2018, at 3:26 PM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2018-05-30 at 3 25 48 pm]<https://user-images.githubusercontent.com/39458325/40719930-c1d0794c-641d-11e8-81a4-1e638f537a77.png>

got the same error in next function ...

**Comment by lamatat** [comment] 2018-05-30 12:32
you just to do pod update?
or do you have a version number to add in podfile?

**Comment by MoathOthman** [comment] 2018-05-30 17:07
@lamatat you can use pod 'MOLH',:git => 'https://github.com/MoathOthman/MOLH.git'

**Comment by lamatat** [comment] 2018-05-31 07:07
i got this [!] Unable to find a specification for 'MOLH'.

**Comment by MoathOthman** [comment] 2018-05-31 08:02
@lamatat 

> i got this [!] Unable to find a specification for 'MOLH'.

its fixed now , thanx for pointing it out. please try again.

**Comment by lamatat** [comment] 2018-05-31 08:33
am getting the same error even after updating the pod

![screen shot 2018-05-31 at 11 32 19 am](https://user-images.githubusercontent.com/39458325/40771558-56bf4ef4-64c6-11e8-81ae-3c5728dc697d.png)

**Comment by MoathOthman** [comment] 2018-06-01 21:41
@lamatat can you debug it , print the result of userdef.object(forkey: ....)

**Comment by lamatat** [comment] 2018-06-01 21:50
got this: 
Optional(<__NSSingleObjectArrayI 0x125d6bd70>(
ar
)
)
before crashing...

**Comment by MoathOthman** [comment] 2018-06-01 21:58
NSSingleObjectArray!, interesting , I think you have only one language for the device which is arabic, right? , if you go to settings app -> general -> languages , you should see one language, right?

**Comment by lamatat** [comment] 2018-06-01 22:04
no there's 2 .. english and arabic

**Comment by lamatat** [comment] 2018-06-01 22:07
sorry i was running the app with arabic language x_x
now changed it to system language and got this:
Optional(<__NSCFArray 0x13de224a0>(
ar,
en
)
)

**Comment by MoathOthman** [comment] 2018-06-01 23:15
@lamatat do you still get the crash then?

**Comment by lamatat** [comment] 2018-06-02 00:34
yes i do 
same crash as the screenshot above

**Comment by MoathOthman** [comment] 2018-06-02 21:16
mmmm, thats really weird. is there any environment factors you have, did you try it on device while not in debug mode? 
I updated the code to swift 4 , can you pod install again and try?

**Comment by lamatat** [comment] 2018-06-03 07:07
same :(
please help me solve this T_T

**Comment by lamatat** [comment] 2018-06-03 07:36
found out something ...
this is only happens when used in: class TextField: UITextField for example...
any idea?

**Comment by MoathOthman** [comment] 2018-06-03 09:45
@lamatat  since textfield functionality is not that perfect, 
comment out the line where its swizzled ..
`swizzle(class:UITextField.self, sel: #selector(UITextField.layoutSubviews), override: #selector(UITextField.cstmlayoutSubviews))`

**Comment by lamatat** [comment] 2018-06-05 06:58
just found something ...
this has nothing to do with your library ...
because i have tried:
        let pre = Locale.preferredLanguages.first
         if pre == "ar"{
         ......
         }
and got the same error! which is really wired!

sorry for all the trouble but it has nothing to do with your awesome library :)
i have another question i will open new issue if you please can check it out .. thanks

**Closed** 2018-06-05 06:58 UTC

**Comment by MoathOthman** [comment] 2018-06-05 07:10
Thnx for letting me know , please tell us what was the issue when u find the solution.
Thnx

Sent from my iPhone

On Jun 5, 2018, at 9:58 AM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #17<https://github.com/MoathOthman/MOLH/issues/17>.

**Comment by lamatat** [comment] 2018-06-05 07:34
sure.. thanks you :)!
