### ISSUE TITLE
Placeholder for Textfield goes outside the border

### ISSUE THREAD

**Issue by baljit92** [MoathOthman/MOLH#7] opened 2018-03-14 12:12 UTC
Hi,

I am using your `MOLH` pod. The issue is that the custom placeholder text goes outside the field. Please see the screenshot attached.

Thanks
<img width="333" alt="screen shot 2018-03-14 at 3 11 15 pm" src="https://user-images.githubusercontent.com/5225501/37401751-29aafbf2-279a-11e8-84b9-09834594d72b.png">

**Comment by MoathOthman** [comment] 2018-03-14 16:10
@baljit92 can you show the whole textfield and points the limit of it, thnx

**Comment by baljit92** [comment] 2018-03-14 16:44
@MoathOthman I have attached the entire textfield along. So the placeholder text is supposed to "رقم الهاتف" in the `UITextField`. The placeholder text is programmatically created through a `NSMutableAttributedString`.
<img width="322" alt="screen shot 2018-03-14 at 7 39 16 pm" src="https://user-images.githubusercontent.com/5225501/37416894-0d9692de-27c0-11e8-9804-e20f805a76cb.png">

**Comment by MoathOthman** [comment] 2018-03-15 01:22
thats really weird ,
I tried to reproduce it by using 
        textField.attributedPlaceholder = NSAttributedString(string: "بلعلابي هلا")
and it looks fine , 
did you make any other changes that might affected it , like padding Views !!
what happens if you dont set the text alignment. 
MOLH wont touch the placeholder since its of a private type UITextFieldLabel. and you cant set the tag of it unless you made a modification in MOLH and added this

```
extension UILabel: TextViewType {
    public  func cstmlayoutSubviews() {
        self.cstmlayoutSubviews()
        if self.isKind(of: NSClassFromString("UITextFieldLabel")!) {
            self.tag = MOLH.shared.maximumLocalizableTag
        }
        handleSwitching()
    }
}
```

**Comment by baljit92** [comment] 2018-03-15 04:07
Not really. If I don't set the alignment; the placeholder remains on the left side (default). 

This is all I do.


       usernameField.layer.cornerRadius = 10

        usernameField.layer.sublayerTransform = CATransform3DMakeTranslation(usernameField.layer.frame.width/7, 0, 0);

        var myUsernameMutableStringTitle = NSMutableAttributedString()
        let unamePlaceholder = NSLocalizedString("kLoginEmail", comment: "")
        
   
        myUsernameMutableStringTitle = NSMutableAttributedString(string:unamePlaceholder, attributes: [NSFontAttributeName:UIFont(name: "Gill Sans", size: 20)!])
        myUsernameMutableStringTitle.addAttribute(NSForegroundColorAttributeName, value: UIColor(hex:"76777B"), range:NSRange(location:0,length:unamePlaceholder.characters.count))
        
        

        usernameField.attributedPlaceholder = myUsernameMutableStringTitle
        

        if UIApplication.shared.userInterfaceLayoutDirection == UIUserInterfaceLayoutDirection.rightToLeft {
            usernameField.textAlignment = .right

        }
        else {
            usernameField.textAlignment = .left
        }`

**Comment by MoathOthman** [comment] 2018-03-15 14:16
@baljit92 this is the reason
   ` usernameField.layer.sublayerTransform = CATransform3DMakeTranslation(usernameField.layer.frame.width/7, 0, 0);`

why would you use it ? what will happen if you remove it

**Comment by MoathOthman** [comment] 2018-04-27 18:54
will close this as its not active

**Closed by MoathOthman** 2018-04-27 18:54 UTC
