### ISSUE TITLE
reset func not work in version 1.3

### ISSUE THREAD

**Issue by Mohamedawad2020** [MoathOthman/MOLH#59] opened 2020-05-28 14:04 UTC

**Comment by abdallahnh** [comment] 2020-05-28 15:57
@MoathOthman this is happening with me as well, any quick fix for this?

**Comment by MoathOthman** [comment] 2020-05-28 16:05
with using scenedelegate or not? I am on it currently.

**Comment by abdallahnh** [comment] 2020-05-28 16:13
the issue is when y ou are on ios 13 and you are not using scene

**Comment by abdallahnh** [comment] 2020-05-28 16:14
`open class func reset(transition: UIView.AnimationOptions, duration: Float = 0.5) {
        if #available(iOS 13.0, *) {
          ----->>>  for scene in UIApplication.shared.connectedScenes {
                (scene.delegate as? MOLHResetable)?.reset()
            }
        } else {
            if let delegate = UIApplication.shared.delegate {
                if delegate is MOLHResetable {
                    (delegate as!MOLHResetable).reset()
                }
                UIView.transition(with: ((delegate.window)!)!, duration: TimeInterval(duration), options: transition, animations: {})
            }
        }
    }`

it will enter ---> this line and see no scene so will not call the reset delegate

**Comment by MoathOthman** [comment] 2020-05-28 16:16
let me fix it.

**Comment by MoathOthman** [comment] 2020-05-28 16:34
fixed in 1.4, please try that @Mohamedawad2020 @abdallahnh

**Closed** 2020-05-28 16:34 UTC
